defaults:
  - _self_
  - encoder: default.yaml
  - variance_adaptor: default.yaml
  - decoder: default.yaml
  - postnet: default.yaml
  - optimizer: adam.yaml

_target_: fs2.models.fastspeech2.FastSpeech2
n_vocab: 178
n_spks: ${data.n_spks}
spk_emb_dim: ${model.encoder.d_model}
n_feats: 80
data_statistics: ${data.data_statistics}
add_postnet: true
